name: Patti Ann Design
favicon: null
layout_spectrum: 0.09791127359494567
typography_spectrum: 0.04868657072074711
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.47539734188467264
  lightness: 0.7707043252885342
  saturation: 0.9676913551520556
  rhythmicContrast: 0.6659599537961185
purpose: []
